#show link: underline

= Algorithmic Work Completed

- After switching to the scenario generation project, I started exploring the use of LLMs for generating simulation scenarios. I started by exploring the Scenic language, which focuses on generating scenarios for autonomous driving. The language has a complex grammar and syntax which is compiled to Python code. It has support for various simulators, the most comprehensive of which is CARLA. I was able to get simple scenarios generated by LLMs to run in CARLA, but more complex scenarios (i.e. overtaking maneuvers) were unsuccessful. Currently, the language only supports generating scenarios for 2-dimensional roadmaps, which might limit its applicability to other domains or more complex autonomous driving scenarios.

// maybe a good idea to use 2-stage LLM generation approach. First generating the map/terrain for the engine to process, then using further prompting combined with the high-level map definition to add actors and behaviors.
- After identifying some of these limitations, I aimed to develop a more general LLM-based architecture for scenario generation that could be adapted to other domains, such as flight, robotics, or combat. This architecture aims to use LLMs to convert natural language into structured scenario representations that can be interpreted by the engines used by simulators. 

#figure(
  image("figures/general-scenario-generation-architecture.png", width: 80%),
  caption: [My Proposed General Architecture for LLM-Based Scenario Generation]
) <general-scene-gen-arch>

#figure(
  image("figures/simulator-specific-scenario-generation-architecture.png", width: 80%),
  caption: [My Proposed Simulator-Specific Architecture for LLM-Based Scenario Generation]
) <general-scene-gen-arch>

#figure(
  image("figures/example-ads-text-prompt.png", width: 80%),
  caption: [An example text prompt for generating an ADS scenario. Taken from: #link("https://arxiv.org/pdf/2505.14881")[TrafficComposer]]
) <ads-text-prompt>

= System Work Completed

- #link("https://docs.google.com/spreadsheets/d/1mP5MKvrYigHIMJ6TY9hsoBWEXbnDSMNOM_kjwNvGTwU/edit?usp=sharing")[(RF attack survey)]
- #link("https://docs.google.com/spreadsheets/d/1ZDF_UFl231P4fEPDDRGzZn4KaLvrHr4gin7GnBA64hs/edit?usp=sharing")[(LLM scenario generation survey)]

= How Can the Group Improve to Make CSPL More Enjoyable While Maintaining Productivity?

- I think I could have benefitted from more frequent or detailed discussions to reduce ambiguity about my research directions. For example, My initial rotation project plan was to build a CPS attack simulation platform using MATLAB/Simulink. Initially, I thought this idea and the implementation plan was well-received. However, after spending a week trying to implement the plan, we had a meeting and decided that simulation would be insufficient for the project, prompting me to pivot to a different idea.

= Timeline of My Rotation

== Week 1 (08/25-08/31)

- Identified possible direction for rotation project (adversarial robustness of CPS) and presented on an initial paper in the area

== Week 2 (09/01-09/07)

- Further work on literature review over CPS sensor attacks and identifying a concrete rotatino project.

== Week 3 (09/08-09/14)

- Discussed with Shanghao about a possible project for the rotation. We came to trying to simulate IMU/GPS spoofing attacks on drones using MATLAB/Simulink

- Developed implementation plan for building a CPS attack simulation platform using MATLAB/Simulink

- Started trying to setup initial components of the platform by integrating a drone model from Simulink

== Week 4 (09/15-09/21)

- Continued working on building a CPS attack simulation platform using MATLAB/Simulink

- Started trying to setup an RF transmitter model in Simulink for simulating EMI signal injection attacks on CPS

- Pivoted away from designing the MATLAB/Simulink platform to focus on assessing practical feasibility of RF attacks on CPS

== Week 5 (09/22-09/28)

- Surveyed recent works in EMI signal injection attacks on CPS and tried to identify the physics behind each attack #link("https://docs.google.com/spreadsheets/d/1mP5MKvrYigHIMJ6TY9hsoBWEXbnDSMNOM_kjwNvGTwU/edit?usp=sharing")[(RF attack survey)]

- Attempted to idenfiy a possible RF attack that could be quick to replicate with a HackRF module.

== Week 6 (09/29-10/05)

- Pivoted away from analyzing practical feasibility of RF attacks on CPS to exploring use of LLMs for scenario generation in autonomous driving

- Cloned Scenic repository and review documentation

- Looked at possibility of fine-tuning LLMs on Scenic code generation. Deemed unlikely to be successful due to limited amount of training data.

- Got LLM agent to create simple driving scenarios using Scenic

- Setup CARLA simulator to render scenarios generated by LLMs using Scenic

== Week 7 (10/06-10/12)

- Rendered simple driving scenarios in CARLA using Scenic code generated by LLMs

- Attempted to get LLMs to generate more complex scenarios (i.e. overtaking maneuvers) but was unsuccessful

- Investigated possibility of using LLMs to generate the roadmaps for vehicles and pedestrians (i.e. OpenDRIVE files) for simulators like CARLA - deemed to be too time consuming for little gain

- Investigated recent works in LLM-based scenario generation for autonomous driving #link("https://docs.google.com/spreadsheets/d/1ZDF_UFl231P4fEPDDRGzZn4KaLvrHr4gin7GnBA64hs/edit?usp=sharing")[(LLM scenario generation survey)]

- Met with VBS4 representatives to discuss applicability of their simulator/SDK for combat-focused adversarial sticker and scenario generation

== Week 8 (10/13-10/17)

- Reviewed code from similar works and started identifying methods to adapt these ideas to other problem domains (i.e. flight, robotics, combat)
- Proposed Architectures for LLM-Based Scenario Generation outside of autonomous driving domain
- Created this wrap-up document

